import Vue from 'vue';
import 'vuetify/src/stylus/app.styl';
import Vuetify, {
  VApp, // required
  VNavigationDrawer,
  VFooter,
  VToolbar,
  VFadeTransition,
  VSpacer,
  VToolbarTitle,
  VToolbarItems,
  VBtn,
  VContainer,
  VLayout,
  VFlex,
  VDivider,
  VIcon,
  VList,
  VListTileTitle,
  VListTileSubTitle,
  VListTileAvatar,
  VListTileAction,
  VListTileContent,
  VListTileActionText,
  VListTile,
  VImg,
  VAutocomplete,
  VDataTable,
  VCheckbox,
  VDatePicker,
  VMenu,
  VTextField,
  VForm,
  VTabs,
  VTabItem,
  VTab,
  VCard,
  VCardText,
  VCardTitle,
  VCardActions,
  VCardMedia,
  VTabsSlider,
  VTabsItems,
  VSwitch,
  VRadioGroup,
  VRadio,
  VDialog,
  VAvatar,
  VStepper,
  VStepperHeader,
  VStepperContent,
  VStepperItems,
  VStepperStep,
  VBadge,
  VTextarea,
} from 'vuetify/lib';

Vue.use(Vuetify, {
  theme: {
    primary: '#52A8B6',
    secondary: '#DCDEE1',
    accent: '#BBE4EA',
    error: '#F27171',
    success: '#7AC1D0',
    info: '#5585B5',
    warning: '#F2D30C',
  },
  components: {
    VApp,
    VNavigationDrawer,
    VFooter,
    VToolbar,
    VFadeTransition,
    VSpacer,
    VToolbarTitle,
    VToolbarItems,
    VBtn,
    VContainer,
    VLayout,
    VFlex,
    VDivider,
    VIcon,
    VList,
    VListTileTitle,
    VListTileSubTitle,
    VListTileAvatar,
    VListTileAction,
    VListTileContent,
    VListTileActionText,
    VListTile,
    VImg,
    VAutocomplete,
    VDataTable,
    VCheckbox,
    VDatePicker,
    VMenu,
    VTextField,
    VForm,
    VTabs,
    VTabItem,
    VTab,
    VCard,
    VCardText,
    VCardTitle,
    VCardActions,
    VCardMedia,
    VTabsSlider,
    VTabsItems,
    VSwitch,
    VRadioGroup,
    VRadio,
    VDialog,
    VAvatar,
    VStepper,
    VStepperHeader,
    VStepperContent,
    VStepperItems,
    VStepperStep,
    VBadge,
    VTextarea,
  },
  iconfont: 'md',
});

